server:
  port: 8766
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zone-ams
  datasource:
    url: jdbc:mysql://localhost:3306/zone_ams?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      database: 0
      host: localhost
      password:
      port: 6379
  jpa:
    show-sql: true

